version: '3.9'

services:
  setup:
    container_name: setup_box
    build:
      context: .
      dockerfile: setup/Dockerfile.setup
    environment:
      run_mode: ${run_mode}
    volumes:
      - ./:/app
    restart: on-failure
    networks:
      - jt_network

  database_prod:
    container_name: jt_pg_container
    image: postgres:14.6
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: jt_db
    volumes:
       - jt_pg_vol_prod:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - jt_network

  database_test:
    container_name: test_jt_pg_container
    image: postgres:14.6
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: test_jt_db
    volumes:
       - jt_pg_vol_test:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - jt_network

  frontend:
    container_name: jt_frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - ./:/app
      - jt_pg_vol_prod:/var/lib/postgresql/data
      - jt_pg_vol_test:/var/lib/postgresql/data
    restart: on-failure
    ports:
      - '5000:5000'
    environment:
      run_mode: ${run_mode}
    links:
      - database_prod
      - database_test
    networks:
      - jt_network

volumes:
  jt_pg_vol_prod:
    name: jt_pg_vol_prod
  jt_pg_vol_test:
    name: jt_pg_vol_test

networks:
  jt_network:
    name: jt_network