FROM python:3.8-slim-buster

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt
RUN apt-get update
RUN apt-get -y install postgresql

RUN pwd

CMD ["tail", "-f", "/dev/null"]
